$ENV{'TEXINPUTS'}='texmf//:' . $ENV{'TEXINPUTS'};
$ENV{'T1FONTS'}='texmf/fonts/type1//:' . $ENV{'T1FONTS'};
$ENV{'AFMFONTS'}='texmf/fonts/afm//:' . $ENV{'AFMFONTS'};
$ENV{'TEXFONTMAPS'}='texmf/fonts/map//:' . $ENV{'TEXFONTMAPS'};
$ENV{'TFMFONTS'}='texmf/fonts/tfm//:' . $ENV{'TFMFONTS'};
$ENV{'VFFONTS'}='texmf/fonts/vf//:' . $ENV{'VFFONTS'};
$ENV{'ENCFONTS'}='texmf/fonts/enc//:' . $ENV{'ENCFONTS'};